### ISSUE TITLE
Implement minicran's main functions

### ISSUE THREAD

**Issue by sdhutchins** [datasnakes/rut#2]
- [ ] `pkgDep()` - Find package dependencies
- [ ] `makeRepo()` - Make repository (with or without downloading packages)
- [ ] `addPackage()` - Add additonal packages (and their dependencies) to existing repository
- [ ] `updatePackages()` - Update the versions of packages currently in the repository

**Comment by grabear** [comment]
This is currently unnecessary for moving forward. Closing for now.
