### ISSUE TITLE
Ensure minicran's system requirements are met and/or documented

### ISSUE THREAD

**Issue by sdhutchins** [datasnakes/rut#3]
### System requirements

The miniCRAN package itself doesn't introduce any system dependencies. However, the package imports the curl and XML packages. These have system requirements on libxml2-devel, libcurl-devel and openssl-devel.

On systems with the rpm package manager (Red Hat, CentOS) try:

  ```
  yum install libcurl-devel libxml2-devel openssl-devel
  ```
On systems with the aptitude package manager (Debian, Ubuntu) try:

  ```
  apt-get install libcurl4-openssl-dev libxml2-devel openssl-devel
  ```

**Comment by grabear** [comment]
This is currently unnecessary for moving forward. Closing for now.
